server:
  port: 10000    #服务端口号
eureka:
  instance:
    hostname: localhost #主机名
  client:
    registerWithEureka: false #禁止注册中心注册自己
    fetchRegistry: false      #禁止检索服务
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
  application:
    name: config-server