eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/  #注册中心服务地址
#server:
#  port: 8900  #当前服务端口
#spring:
#  application:
#    name: consumer  #当前服务名 consumer
#开启熔断器
feign:
  hystrix:
    enabled: true

