eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/  #注册中心服务地址
server:
  port: 10900  #当前服务端口
spring:
  application:
    name: service-zuul #服务名
zuul:
  routes:  #配置路由
    api-a:
      path: /api-a/**
      serviceId: consumer   #api-a 开头的请求跳转到  consumer1服务
    api-b:
      path: /api-b/**
      serviceId: consumer2   #api-b 开头的请求跳转到 consumer2服务